language: rust
matrix:
  include:
    - name: "miri"
      rust: nightly
      script:
        - rustup toolchain install nightly-2021-03-25
        - rustup default nightly-2021-03-25
        - rustup component add miri
        - cargo miri setup
        - cargo miri test
    - name: "debug"
      rust: stable
      script:
        - cargo test --verbose --all
